# Generated by Django 5.1 on 2024-09-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pitchNum", models.IntegerField()),
                ("date", models.DateField()),
                ("pitcher", models.CharField(max_length=50)),
                ("pitcherID", models.IntegerField()),
                ("pitcherHanded", models.CharField(max_length=50)),
                ("batter", models.CharField(max_length=50)),
                ("batterID", models.IntegerField()),
                ("batterHanded", models.CharField(max_length=50)),
                ("outs", models.IntegerField()),
                ("balls", models.IntegerField()),
                ("strikes", models.IntegerField()),
                ("pitchType", models.CharField(max_length=50)),
                ("Outcome", models.CharField(max_length=50)),
                ("battedBallType", models.CharField(max_length=50)),
                ("inPlayResult", models.CharField(max_length=50)),
                ("velocity", models.DecimalField(decimal_places=6, max_digits=10)),
                ("vertAngle", models.DecimalField(decimal_places=6, max_digits=10)),
                ("horzAngle", models.DecimalField(decimal_places=6, max_digits=10)),
                ("spinRate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("spinDegree", models.DecimalField(decimal_places=6, max_digits=10)),
                ("vertRelease", models.DecimalField(decimal_places=6, max_digits=10)),
                ("horzRelease", models.DecimalField(decimal_places=6, max_digits=10)),
                ("extension", models.DecimalField(decimal_places=6, max_digits=10)),
                ("inducedVert", models.DecimalField(decimal_places=6, max_digits=10)),
                ("horzBreak", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "plateLocHeight",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("plateLocSide", models.DecimalField(decimal_places=6, max_digits=10)),
                ("VertApprAngle", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "HorzApproachAngle",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("ExitVelo", models.DecimalField(decimal_places=6, max_digits=10)),
                ("LaunchAngle", models.DecimalField(decimal_places=6, max_digits=10)),
                ("LaunchDirect", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "LaunchDistance",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("catcher", models.CharField(max_length=50)),
            ],
        ),
    ]
