# Generated by Django 5.1 on 2024-09-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playerData", "0002_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="playerData/excel"),
        ),
    ]
