# Generated by Django 5.1 on 2024-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playerData", "0003_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitch",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
