# Generated by Django 5.1 on 2024-09-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playerData", "0004_alter_pitch_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitch",
            name="ExitVelo",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="HorzApproachAngle",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="LaunchAngle",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="LaunchDirect",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="LaunchDistance",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="Outcome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="VertApprAngle",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="balls",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="battedBallType",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="batter",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="batterHanded",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="batterID",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="catcher",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="extension",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="horzAngle",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="horzBreak",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="horzRelease",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="inPlayResult",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="inducedVert",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="outs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="pitchNum",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="pitchType",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="pitcher",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="pitcherHanded",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="pitcherID",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="plateLocHeight",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="plateLocSide",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="spinDegree",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="spinRate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="strikes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="velocity",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="vertAngle",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="vertRelease",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
